# Generated by Django 4.2.20 on 2025-04-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweets",
            name="likes",
        ),
    ]
